jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - 11
        - 10
      script:
        - npm run test
      notifications:
        email:
          on_success: never
          on_failure: always
